### ISSUE TITLE
[Vote] for our (first) official library language

### ISSUE THREAD

**Issue by moul** [pathwar/api.pathwar.net#25]
We need to choose a language (and library) for our first official API client.

Our tools will use this client, so we need to think about a language that let us call system commands

---

Non-exhaustive list of tools we will need to build : 
- level-host daemon
- statistics cron
- day-to-day admin CLI scripts

---

Languages : 
- **Python**: 3
- **Node.js**: 1
- **Go**: 0

---

Please vote for your favorite language(s), you can pick multiple answer, also you can add comments to help us choose

If you know good libraries to build API clients, link them also

cc @cerisier @aimxhaisse @mlequeux @Solvik @blotus

**Comment by moul** [comment]
I vote for both of these : 
- node.js is cool to build server scripts and also to build web libraries (using browserify), and perfect to build realtime applications
- python is cool to build server scripts and maybe easier to be used by everyone

---

GO is cool and amazing for the ease of deployment on multi architectures, and it's the best language to manipulate Docker containers but it will be to difficult to code with for everyone and the codebase will be bigger I think :/

**Comment by mlequeux** [comment]
- Python for the same reasons

**Comment by aimxhaisse** [comment]
- Python for the 1st

**Comment by moul** [comment]
Let's go for Python, now, do you have any suggestion about : 
- some interesting libraries to build python api-client ?
- some nicely-designed python api-client projects on Github ?

**Comment by mlequeux** [comment]
* Flask

**Comment by mlequeux** [comment]
- [Requests](http://docs.python-requests.org/en/latest/)

**Comment by cerisier** [comment]
- https://github.com/scastillo/siesta (prefered)
- https://github.com/jaimegildesagredo/finch
- https://github.com/danudey/pyREST

And @moul already found the awesome:
- https://github.com/samgiles/slumber
