### ISSUE TITLE
Review model ACLs

### ISSUE THREAD

**Issue by moul** [pathwar/api.pathwar.net#62]
- [x] achievements
- [x] activities
- [x] coupons
- [x] infrastructure-hijacks
- [x] items
- [x] level-hints
- [x] level-instance-users
- [x] level-instances
- [x] level-statistics
- [x] levels
- [x] organization-achievements
- [x] organization-coupons
- [x] organization-items
- [x] organization-level-hints
- [x] organization-level-validations
- [x] organization-levels
- [x] organization-statistics
- [x] organization-users
- [x] organizations
- [x] servers
- [x] sessions
- [x] user-hijack-proofs
- [x] user-notifications
- [x] user-organization-invites
- [x] user-tokens
- [x] users
- [x] whoswho-attempts

**Comment by moul** [comment]
Views:
- users: users, raw-users, accounts
- organizations: organizations, raw-organisations, teams
- user-notifications: user-notifications, raw-user-notifications

**Comment by aimxhaisse** [comment]
:beer:

**Comment by cerisier** [comment]
:man_with_gua_pi_mao: :ok_hand:
