### ISSUE TITLE
People must be able to buy hints, but we should also give hints automatically 1 day after buying a level, 1 week after etc

### ISSUE THREAD

**Issue by moul** [pathwar/api.pathwar.net#81]

**Comment by sylvainkalache** [comment]
Another idea would be that if you solve an issue without using hint, you receive maximum coins. For every hint you use, you loose coins that you can potentially win

**Comment by moul** [comment]
Yes, I prefer this method, so people can buy more levels :+1:

**Comment by moul** [comment]
Plus, people must validate levels faster, amazing, :)
